Code Review!!
IjayAbby/YouTube-Clone pull request #1
Opened 2020-07-12 23:09 UTC by IjayAbby

A request for Code Review for the HTML & CSS Course on Embedding Images and Video.

2020-07-12 23:56 UTC, bertil291utn requested changes
**Status:** Changes requested 🔴  :shipit:? Not yet.

# Hey guys, you've been doing a great job, and also I hope you enjoyed coding.

But in order to accomplish as the actual page, you required to do these changes, listed below: 

##### Mandatory changes

- [ ] Students **are not required** to add GitHub Actions as linters are required starting from the second project, therefore please remove your `.github/workflows/linters.yml` directory
-[ ] Check inline comments.

<img src="https://user-images.githubusercontent.com/24902525/87258986-a3fd7e80-c46d-11ea-9395-20e2cb6b6e02.png" alt="image" style="zoom:67%;" />

##### Optional changes

- [ ] Try to use [`<footer>`](https://www.w3schools.com/TagS/tag_footer.asp) tag for the footer.

- [ ] You might use a better reset CSS file. Like [normalize](https://necolas.github.io/normalize.css/8.0.1/normalize.css) [1]

- [ ] Consider use hex color instead rgb.[1]



###### _[1] [Good and bad  CSS practices](https://speckyboy.com/good-bad-css-practices/)_



<hr>


Guys work in the requested changes above and request another review.
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-07-12 23:56 UTC, bertil291utn commented on css/styles.css
> +
## Using the Same Rule Repetitively

- [ ] Avoid repeat `display: flex;` rule many times. 
Try like so:
````
.flex{
 display: flex;
}
````
Then add in your HTML elements where you require

`<div class="flex">`

2020-07-12 23:56 UTC, bertil291utn commented on css/styles.css
> +}
You have `recommended-video` class twice.
- [ ] Please merge those ones

2020-07-12 23:56 UTC, bertil291utn commented on index.html
> +                        <section class="about-uploader">
## Using Inline Styles
 - [ ] Avoid using inline styles. Move all your styles to CSS files

2020-07-13 01:20 UTC, bertil291utn requested changes
**Status:** Changes requested 🔴  :shipit:? Not yet.

# Hey guys, you've been doing a great job.

All your changes seem amazing, however, you need to be careful about your last change related with `display flex:`,  check inline comments.

<hr>

Guys work in the requested changes above and request another review. 
Good luck. 

> “Never stop, never conform until what is good becomes even better, and what’s better becomes excellent.”

2020-07-13 01:20 UTC, bertil291utn commented on css/styles.css
>      justify-content: space-between;
## Remove `display:flex;` rule
If you have already a class `.flex{display:flex;}` declared, please remove all **display:flex** rules in your entire CSS file

2020-07-13 08:47 UTC, IjayAbby commented on css/styles.css
>      justify-content: space-between;
Refactored our CSS & Index.html file to fix the issue.

2020-07-13 09:08 UTC, HADDADSOHAIB approved these changes
### Status: Project Approved :+1: 

### Hi @IjayAbby and @ggotora :hand: 

### Great Job, you implemented all the required changes by the previous TSE, you can go and merge this branch into master. However, this is some optional requirements that you could do before you merge:
- [Optional] Use the `<nav></nav>` tag for the navbar.
- [Optional] The share icon should be a button.

2020-07-13 09:23 UTC, merged